spring:
  application:
    name: kitchen

  datasource:
    url: jdbc:postgresql://localhost:5435/kitchen_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: kitchen-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: "ru.Liga.dto"
        spring.json.value.default.type: "ru.Liga.dto.KitchenOrderRequestDto"
app:
  kafka:
    topics:
      kitchen-to-waiter: "kitchen-to-waiter"
    groups:
      kitchen: "kitchen-group"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    ru.Liga.waiter: DEBUG
server:
  port: 8082
